// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxs7LUoHUVf5YTg8FrYvsC0qf4_-2eAy8',
    appId: '1:808957040758:web:73eed5dae7f17f08df2757',
    messagingSenderId: '808957040758',
    projectId: 'app-taller-2',
    authDomain: 'app-taller-2.firebaseapp.com',
    databaseURL: 'https://app-taller-2-default-rtdb.firebaseio.com',
    storageBucket: 'app-taller-2.firebasestorage.app',
    measurementId: 'G-0T6DXYX564',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_2vvqbQd-zWX_buNgCwKDWPR2UQdt0lw',
    appId: '1:808957040758:android:8623ed88764a984edf2757',
    messagingSenderId: '808957040758',
    projectId: 'app-taller-2',
    databaseURL: 'https://app-taller-2-default-rtdb.firebaseio.com',
    storageBucket: 'app-taller-2.firebasestorage.app',
  );
}
